### ISSUE TITLE
/api/docvalues/{field}/binary causes a NullPointerException

### ISSUE THREAD

**Issue by noofherder** [flaxsearch/marple#2]
http://localhost:8080/api/docvalues/text/binary using my local HE index.

**Comment by sarowe** [comment]
The fix I committed on my fork assumes that the NPE is as a result of non-existent field or non-existent (binary,etc.) doc values on an existing field.  I added a test for the former.

I looked for other error handling in the app and I didn't find any, so it'd be good to come up with a standard strategy.  E.g. I found this site that talks about making error responses be JSON instead of the default text format: https://nbsoftsolutions.com/blog/writing-a-dropwizard-json-app

**Comment by sarowe** [comment]
Crap, I meant to commit only to a new branch for the fix, but instead committed to master (on my fork).  Hope that doesn't cause trouble - I'll be more careful next time.

**Comment by sarowe** [comment]
Ugh.  I think I've cleaned up the problem (reverted the commit on master - yes, twice :( - and cherry-picked the commit onto a new branch `issue-2-fix-dv-npe`), but I had to create a pull request for the new branch because it didn't automatically get linked to this issue: https://github.com/flaxsearch/marple/pull/4

**Comment by romseygeek** [comment]
bq. it'd be good to come up with a standard strategy

I like your solution above, just returning a 404.  Let's keep this as simple as possible for now!
